"""ISCX-Tor2016 loader.

Chosen as a third corpus for one specific reason: it is the only dataset we
could find that provides a grouping axis which is **neither temporal nor
per-file**. The collection design captured the same activity simultaneously at
the workstation and at the gateway, releasing paired pcap files. That gives
`vantage` as a split axis, so the split-protocol comparison becomes three-way
rather than two-way, and a result that holds across a non-temporal,
non-per-file grouping is a materially stronger claim.

Honest limitations, all of which belong in the paper rather than in a
footnote:

* **The capture-task design resembles 5G Traffic, not a backbone corpus.**
  Scripted per-application sessions with two users. What this corpus buys is
  the vantage structure and a documented labelling mechanism, not a third kind
  of collection. Saying otherwise would overclaim.
* **Labels on the Tor side are inherited, not verified per flow.** The
  published procedure extracted flows from the workstation capture, confirmed
  the majority were generated by application X, then labelled *every* flow in
  the corresponding Tor pcap as X. Tor-side labels therefore rest on a
  majority argument taken at the other vantage point. `PROTOCOL.md` records
  this and the audit's identifier probes are the check on it.
* **The non-Tor half is recycled from ISCX-VPN2016.** The two are not
  independent corpora and must not both be used as though they were.
* **The label is a function of the filename.** Same circularity as every
  capture-per-application dataset: grouping on `capture_id` is not optional
  here, it is the minimum honest protocol.

Unverified at the time of writing, because the distribution is behind a
registration form: the exact directory layout, and whether the captures are
``.pcap`` or ``.pcapng``. The reader handles both and reports which it saw, and
the loader fails loudly on anything else rather than silently yielding zero
flows.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from .canonical import row_from_segment
from .flow_builder import FlowAccumulator, FlowSegment
from .pcap import UnsupportedCapture, capture_format, read_packets

ORIGIN = "iscx_tor"

# Token boundaries, not `\b`. Capture filenames separate tokens with `_`, `-`
# and `.`, all of which `\b` treats as *inside* a word: `\bvoip\b` does not
# match `voip_skype`. This bug appeared three times while writing this loader
# -- in the Tor/NonTor patterns, the vantage patterns, and here -- so the
# boundary is defined once and reused.
_TOKEN = r"(?:^|[^a-z0-9])"
# Trailing digits are part of the token, not a boundary: capture files are
# numbered (`spotify2`, `torrent01`, `chat1a`), so `spotify` must match
# `spotify2`.
_END = r"(?:[0-9]*(?:[^a-z0-9]|$))"


def _token(*alternatives: str) -> str:
    """A regex matching any alternative as a whole path token, digits allowed."""
    return _TOKEN + "(?:" + "|".join(alternatives) + ")" + _END


# The eight application categories the dataset's paper defines. Order matters:
# the first match wins, so more specific categories precede the ones whose
# tokens could appear inside them.
CATEGORY_PATTERNS: List[Tuple[str, str]] = [
    ("audio_streaming", _token(r"audio[-_ ]?streaming", "spotify", r"vimeo[-_ ]?audio")),
    ("video_streaming", _token(r"video[-_ ]?streaming", "youtube", "vimeo", "netflix")),
    ("file_transfer", _token(r"file[-_ ]?transfer", "ftp", "sftp", r"skype[-_ ]?file", "scp")),
    ("email", _token("email", "mail", "gmail", "pop3", "imap", "smtp")),
    # voip precedes chat deliberately: `hangouts_audio` is a voice call, and
    # the bare app name `hangouts` would otherwise claim it for chat. The
    # audio-call variants are more specific, so they are tested first.
    ("voip", _token("voip", "voice", r"skype[-_ ]?audio", r"facebook[-_ ]?audio", r"hangouts?[-_ ]?audio")),
    ("chat", _token("chat", "icq", "aim", "hangouts?", r"facebook[-_ ]?chat", r"skype[-_ ]?chat")),
    ("p2p", _token("p2p", "torrent", "bittorrent", "utorrent")),
    ("browsing", _token("browsing", "browse", "web", "http", "firefox", "chrome")),
]

# Which vantage a capture came from. The dataset pairs a workstation capture of
# regular traffic with a gateway capture of the Tor traffic for the same
# activity, so this is recoverable from the path -- but only carefully.
#
# Two traps, both hit on the first attempt at this:
#   * `\btor\b` does not match `tor_skype`, because `_` is a word character.
#     Tokens here are separated by `_`, `-`, `.` and `/`, not by `\b`.
#   * "nontor" contains "tor", and a NonTor capture whose filename happens to
#     contain "gateway" must not be classified as the Tor vantage. Negatives
#     are therefore tested first and the directory outranks the filename.
NON_TOR = re.compile(_TOKEN + r"non[-_ ]?tor" + _END)
IS_TOR = re.compile(_TOKEN + r"tor" + _END)
WORKSTATION = re.compile(_TOKEN + r"workstation" + _END)
GATEWAY = re.compile(_TOKEN + r"gateway" + _END)


@dataclass
class IscxTorConfig:
    root: str = "data/raw/ISCX-Tor-NonTor-2017"
    max_packets: int = 32
    min_packets: int = 8
    idle_timeout_s: float = 10.0
    active_timeout_s: float = 10.0
    max_flows_per_capture: Optional[int] = 4000
    max_packets_per_capture: Optional[int] = None
    seed: int = 42
    # Whether to label rows by the Tor/non-Tor distinction instead of by
    # application. Both tasks are legitimate; the application task is the one
    # comparable to our other corpora.
    label: str = "application"

    def as_dict(self) -> Dict[str, object]:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}


@dataclass
class CaptureStats:
    capture_id: str
    app: str
    service: str
    vantage: str
    capture_format: str = "unknown"
    packets_read: int = 0
    packets_skipped: int = 0
    segments_seen: int = 0
    segments_kept: int = 0
    error: str = ""

    def as_dict(self) -> Dict[str, object]:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}


def infer_vantage(relative: str) -> str:
    """'gateway', 'workstation', or 'unknown' for a capture's relative path.

    Directory components are consulted before the filename, because the
    release is organised Tor/NonTor at the directory level and a filename can
    contain a misleading token. Returns 'unknown' rather than guessing when
    the path says nothing -- an unknown vantage disables the vantage-disjoint
    protocol for that row, which is the correct failure.
    """
    parts = [component.lower() for component in relative.split("/")]
    directories, filename = parts[:-1], parts[-1] if parts else ""
    for scope in (directories, [filename]):
        text = " ".join(scope)
        if not text:
            continue
        # Negative first: "nontor" contains "tor".
        if NON_TOR.search(text) or WORKSTATION.search(text):
            return "workstation"
        if IS_TOR.search(text) or GATEWAY.search(text):
            return "gateway"
    return "unknown"


def classify_path(path: Path, root: Path) -> Tuple[str, str]:
    """(service, vantage) inferred from the capture's path."""
    relative = str(path.relative_to(root)) if root in path.parents else path.name
    lowered = relative.lower()
    service = "unknown"
    for name, pattern in CATEGORY_PATTERNS:
        if re.search(pattern, lowered):
            service = name
            break
    return service, infer_vantage(relative)


def app_from_path(path: Path) -> str:
    """The capture task name, which is the finest label the corpus provides."""
    return re.sub(r"[^a-z0-9]+", "_", path.stem.lower()).strip("_") or "unknown"


def find_captures(config: IscxTorConfig) -> List[Path]:
    root = Path(config.root)
    if not root.exists():
        raise FileNotFoundError(
            f"{root} does not exist. ISCX-Tor2016 is behind a registration form at "
            "http://cicresearch.ca/CICDataset/ISCX-Tor-NonTor-2017/ -- see "
            "scripts/download_data.sh. Extract the captures under this directory."
        )
    found = sorted(p for p in root.rglob("*") if p.suffix.lower() in {".pcap", ".pcapng"})
    if not found:
        raise FileNotFoundError(
            f"No .pcap or .pcapng files under {root}. The distribution also ships ARFF flow "
            "files, which carry no addresses or timestamps and therefore cannot support any "
            "grouped split protocol; this loader needs the raw captures."
        )
    return found


def extract_capture(path: Path, root: Path, config: IscxTorConfig) -> Tuple[List[FlowSegment], CaptureStats]:
    """Stream one capture into conversation segments."""
    service, vantage = classify_path(path, root)
    stats = CaptureStats(
        capture_id=str(path.relative_to(root)) if root in path.parents else path.name,
        app=app_from_path(path),
        service=service,
        vantage=vantage,
    )
    segments: List[FlowSegment] = []
    accumulator = FlowAccumulator(
        max_packets=config.max_packets,
        idle_timeout_s=config.idle_timeout_s,
        active_timeout_s=config.active_timeout_s,
    )
    capacity = config.max_flows_per_capture
    rng = np.random.default_rng(_capture_seed(config.seed, stats.capture_id))
    seen = 0

    def collect(finished) -> None:
        nonlocal seen
        for segment in finished:
            stats.segments_seen += 1
            if segment.n_packets < config.min_packets:
                continue
            # Reservoir, so the retained flows span the whole capture rather
            # than its opening minutes.
            if capacity is None or len(segments) < capacity:
                segments.append(segment)
            else:
                position = int(rng.integers(0, seen + 1))
                if position < capacity:
                    segments[position] = segment
            seen += 1

    try:
        stats.capture_format = capture_format(path)
        for packet in read_packets(path, config.max_packets_per_capture):
            stats.packets_read += 1
            # Endpoints are canonicalised so both directions of a conversation
            # land in one flow; the lower-port side is taken as the server,
            # which is the standard heuristic and is used only for grouping.
            source, destination = packet.source, packet.destination
            if source[1] <= destination[1]:
                server, client, direction = source, destination, -1
            else:
                server, client, direction = destination, source, 1
            collect(
                accumulator.add(
                    key=(packet.protocol, client[0], client[1], server[0], server[1]),
                    timestamp=packet.timestamp,
                    length=float(packet.length),
                    direction=direction,
                    protocol=packet.protocol,
                    server_ip=server[0],
                    server_port=server[1],
                )
            )
    except UnsupportedCapture as exc:
        stats.error = str(exc)
        return [], stats

    collect(accumulator.flush_all())
    stats.segments_kept = len(segments)
    return segments, stats


def _capture_seed(seed: int, capture_id: str) -> int:
    import hashlib

    return int(hashlib.sha256(f"{seed}:{capture_id}".encode("utf-8")).hexdigest()[:8], 16)


def rows_from_capture(
    segments: List[FlowSegment], stats: CaptureStats, start_index: int, config: IscxTorConfig
) -> List[Dict[str, object]]:
    """Canonical rows for one capture."""
    is_tor = stats.vantage == "gateway"
    rows: List[Dict[str, object]] = []
    for offset, segment in enumerate(segments):
        rows.append(
            row_from_segment(
                segment,
                origin=ORIGIN,
                capture_id=stats.capture_id,
                index=start_index + offset,
                app=stats.app,
                # The Tor/non-Tor task and the application task are both
                # legitimate; which one is the label is a config choice, not a
                # property of the data.
                service=("tor" if is_tor else "nontor") if config.label == "tor" else stats.service,
                vantage=stats.vantage,
            )
        )
    return rows
