#!/usr/bin/env python3
"""Regenerate every table and figure from results/.

    python scripts/make_paper_assets.py --results results --out paper

Tables are LaTeX, figures are vector PDF, and neither is ever edited by hand.
A cell whose run did not happen is written as ``TODO``; it is never filled
with a plausible value, and the script prints a summary of how many TODOs
remain so that an incomplete table cannot be mistaken for a complete one.

Every claim of "better" is looked up in results/significance.json. A
comparison absent from that file is rendered without a significance marker,
not with an optimistic one.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402

from flowconx.analysis.aggregate import aggregate  # noqa: E402

TODO = r"\textsc{todo}"
# A probe whose source column is absent or constant in a corpus *cannot* be
# run. That is different from a cell whose run has not happened yet, and
# rendering both as TODO tells the reader the wrong thing: it implies the
# number is coming.
NOT_APPLICABLE = r"---"
# A comparison the test declined to make: too few seeds for a Wilcoxon
# signed-rank test to have any power. Distinct from TODO (no run) and from
# NOT_APPLICABLE (cannot be run at all), and the distinction matters because
# `undetermined` is not the same as `not significant`.
UNDETERMINED = r"\emph{n.d.}"

# Colourblind-safe (Okabe-Ito). Used for every figure so the paper reads as
# one document rather than as a collection of default matplotlib styles.
PALETTE = ["#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#F0E442", "#000000"]


def latex_escape(text: str) -> str:
    for old, new in (("_", r"\_"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(old, new)
    return text


def fmt(mean: Optional[float], std: Optional[float] = None, places: int = 3) -> str:
    if mean is None or not np.isfinite(mean):
        return TODO
    if std is None or not np.isfinite(std):
        return f"{mean:.{places}f}"
    return f"{mean:.{places}f} $\\pm$ {std:.{places}f}"


def table_wrapper(body: str, caption: str, label: str, columns: str) -> str:
    return "\n".join(
        [
            "% Generated by scripts/make_paper_assets.py. Do not edit by hand.",
            r"\begin{table}[t]",
            r"\centering",
            r"\small",
            f"\\begin{{tabular}}{{{columns}}}",
            r"\toprule",
            body,
            r"\bottomrule",
            r"\end{tabular}",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            r"\end{table}",
            "",
        ]
    )


def _cell(group: Optional[Dict[str, Any]], head: str, metric: str = "macro_f1") -> str:
    """A table cell, or TODO when the run behind it has not happened."""
    if not group:
        return TODO
    stats = group.get("heads", {}).get(head, {}).get(metric)
    if not stats:
        return TODO
    return fmt(stats.get("mean"), stats.get("std"))


def _index(groups: Sequence[Dict[str, Any]]) -> Dict[Tuple[str, str, str], Dict[str, Any]]:
    return {(g["experiment"], g["dataset"], g["split"]): g for g in groups}


# --------------------------------------------------------------------------
# Table 1: split protocol contrast. The measurement contribution.
# --------------------------------------------------------------------------

SPLIT_ORDER = ["random_flow", "session_disjoint", "temporal", "server_disjoint"]
SPLIT_LABEL = {
    "random_flow": "Random flow",
    "session_disjoint": "Session-disjoint",
    "temporal": "Temporal",
    "server_disjoint": "Server-disjoint",
}

# Which experiment supplies each protocol's row. Explicit, so a new experiment
# whose name happens to share a prefix cannot displace the intended one.
SPLIT_EXPERIMENT = {
    "random_flow": "flowconx_random_contrast",
    "session_disjoint": "flowconx_main",
    "temporal": "flowconx_temporal",
    "server_disjoint": "flowconx_server_disjoint",
}


def table_split_contrast(index, datasets: Sequence[str], audit: Dict[str, Any]) -> str:
    """How much the field's usual protocol inflates a published-style number."""
    rows: List[str] = []
    header = ["Split protocol"] + [latex_escape(d) for d in datasets]
    rows.append(" & ".join(header) + r" \\")
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{%d}{l}{\emph{FlowCon-X (prototype head)}} \\" % (len(datasets) + 1))
    # Exact experiment names per protocol. A prefix match on "flowconx_" was
    # enough until baseline runs were renamed to flowconx_main_baseline_*:
    # those also match the prefix, carry a `softmax` head rather than
    # `prototype`, and silently replaced this table's headline row with TODO.
    # Prefix matching over an experiment namespace is a trap; name them.
    for split in SPLIT_ORDER:
        cells = []
        for dataset in datasets:
            group = index.get((SPLIT_EXPERIMENT[split], dataset, split))
            cells.append(_cell(group, "prototype") if group else TODO)
        rows.append(f"{SPLIT_LABEL[split]} & " + " & ".join(cells) + r" \\")

    if audit:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{%d}{l}{\emph{AppScanner (2016), identical splits}} \\" % (len(datasets) + 1))
        for split in SPLIT_ORDER:
            cells = []
            for dataset in datasets:
                entry = (
                    audit.get(dataset, {})
                    .get("splits", {})
                    .get(split, {})
                    .get("baselines", {})
                    .get("appscanner", {})
                )
                value = entry.get("macro_f1")
                if entry.get("status") == "unavailable":
                    cells.append(NOT_APPLICABLE)
                else:
                    cells.append(fmt(value) if isinstance(value, (int, float)) else TODO)
            rows.append(f"{SPLIT_LABEL[split]} & " + " & ".join(cells) + r" \\")

    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Macro-F1 under four split protocols, every method on the identical committed splits. The "
            "random-flow row is the protocol standard in the literature and is reported only as a "
            "contrast: correlated flows from one capture session appear on both sides of it. "
            "\\textbf{The size of that contrast is dataset-dependent}, which is itself the result: on a "
            "corpus of single-session captures a flow's capture is nearly its label, while on a backbone "
            "corpus whose flows are already independent the protocol makes little difference. The caption "
            "deliberately does not assert a direction; read the columns."
        ),
        label="tab:split-contrast",
        columns="l" + "c" * len(datasets),
    )


# --------------------------------------------------------------------------
# Table 2: main comparison against every baseline we could run.
# --------------------------------------------------------------------------

BASELINE_TIERS = [
    ("Identifier shortcuts", ["port_only", "sni_only", "server_ip_only", "server_asn_only", "protocol_only"]),
    # first10/first20_sizes are included because on CESNET the 20-packet-size
    # XGBoost is the strongest classical baseline and the one that beats us.
    # An earlier version of this list omitted them, which flattered the model
    # by hiding its closest competitor.
    (
        "Classical statistical",
        ["five_stat", "flow_meta", "size_histogram", "first10_sizes", "first20_sizes", "cumul", "appscanner", "kfp"],
    ),
    ("Deep, non-pretrained", ["deeppacket_cnn", "fsnet", "lstm_attention", "mlp_stats"]),
]
PRETTY = {
    "port_only": "Destination port only",
    "sni_only": "SNI string only",
    "server_ip_only": "Server IP / prefix only",
    "server_asn_only": "Server AS only",
    "protocol_only": "Transport protocol only",
    "five_stat": "5 flow statistics (RF)",
    "size_histogram": "Packet-size histogram (XGB)",
    "first10_sizes": "First 10 packet sizes (XGB)",
    "first20_sizes": "First 20 packet sizes (XGB)",
    "flow_meta": "All flow scalars (XGB)",
    "capture_id_only": "Capture session ID only",
    "cumul": "CUMUL",
    "appscanner": "AppScanner",
    "kfp": "$k$-fingerprinting",
    "deeppacket_cnn": "DeepPacket-style CNN",
    "fsnet": "FS-Net",
    "lstm_attention": "Bi-LSTM + attention",
    "mlp_stats": "Flow-statistics MLP",
    "majority_class": "Majority class",
}


def table_main_comparison(index, audit, dataset: str, split: str) -> str:
    rows: List[str] = [r"Method & Macro-F1 & Balanced acc. & Params \\", r"\midrule"]
    audit_split = audit.get(dataset, {}).get("splits", {}).get(split, {}).get("baselines", {})

    floor = audit_split.get("majority_class", {})
    rows.append(
        f"{PRETTY['majority_class']} & {fmt(floor.get('macro_f1'))} & "
        f"{fmt(floor.get('balanced_accuracy'))} & --- \\\\"
    )
    for tier, families in BASELINE_TIERS:
        rows.append(r"\midrule")
        rows.append(rf"\multicolumn{{4}}{{l}}{{\emph{{{tier}}}}} \\")
        for family in families:
            if family in audit_split:
                entry = audit_split[family]
                if entry.get("status") == "unavailable":
                    # The column this probe reads is absent or constant here.
                    rows.append(
                        f"{PRETTY.get(family, latex_escape(family))} & {NOT_APPLICABLE} & "
                        f"{NOT_APPLICABLE} & --- \\\\"
                    )
                    continue
                rows.append(
                    f"{PRETTY.get(family, latex_escape(family))} & {fmt(entry.get('macro_f1'))} & "
                    f"{fmt(entry.get('balanced_accuracy'))} & --- \\\\"
                )
                continue
            group = index.get((f"flowconx_main_baseline_{family}", dataset, split))
            if group is None:
                rows.append(f"{PRETTY.get(family, latex_escape(family))} & {TODO} & {TODO} & {TODO} \\\\")
                continue
            params = group.get("extras", {}).get("n_parameters", {}).get("mean")
            rows.append(
                f"{PRETTY.get(family, latex_escape(family))} & {_cell(group, 'softmax')} & "
                f"{_cell(group, 'softmax', 'balanced_accuracy')} & "
                f"{int(params):,} \\\\".replace(",", r"\,")
                if params
                else f"{PRETTY.get(family, latex_escape(family))} & {_cell(group, 'softmax')} & "
                f"{_cell(group, 'softmax', 'balanced_accuracy')} & {TODO} \\\\"
            )

    rows.append(r"\midrule")
    ours = index.get(("flowconx_main", dataset, split))
    params = (ours or {}).get("extras", {}).get("n_parameters", {}).get("mean")
    rows.append(
        rf"\textbf{{FlowCon-X}} & \textbf{{{_cell(ours, 'prototype')}}} & "
        rf"{_cell(ours, 'prototype', 'balanced_accuracy')} & "
        + (f"{int(params):,}".replace(",", r"\,") if params else TODO)
        + r" \\"
    )
    return table_wrapper(
        "\n".join(rows),
        caption=(
            f"Main comparison on {latex_escape(dataset)} under the {SPLIT_LABEL.get(split, split).lower()} "
            "protocol, mean $\\pm$ std over seeds, every method on the identical committed splits. "
            "Identifier shortcuts are included deliberately: if one of them approaches the rest, the "
            "benchmark is not measuring traffic analysis. Pre-trained byte-level transformers "
            "(ET-BERT, YaTC, CLE-TFE) are absent because our records retain no payload; see "
            r"\texttt{flowconx/baselines/WHY\_NOT\_RUN.md}."
        ),
        label=f"tab:main-{dataset}",
        columns="lccc",
    )


# --------------------------------------------------------------------------
# Table 3: ablations, with significance.
# --------------------------------------------------------------------------

# Only the rows that were run. The component and hyperparameter sweeps were
# cut deliberately -- see ABLATIONS_CUT in scripts/run_all_experiments.py and
# paper/RESULTS.md -- and the caption declares the table partial rather than
# letting missing rows read as uninteresting ones.
ABLATION_ROWS = [
    ("ablation_full", "Full model"),
    ("ablation_classify_z_app", r"classify from $z_{\mathrm{app}}$"),
    ("ablation_classify_z_network", r"classify from $z_{\mathrm{net}}$"),
    ("ablation_classify_z_concat", r"classify from $z_{\mathrm{app}} \| z_{\mathrm{net}}$"),
    ("ablation_no_adversarial", r"$-$ adversarial nuisance removal"),
    ("ablation_adv_weight_0p0", r"$\lambda_{\mathrm{adv}} = 0$"),
    ("ablation_adv_weight_0p01", r"$\lambda_{\mathrm{adv}} = 0.01$"),
    ("ablation_adv_weight_0p1", r"$\lambda_{\mathrm{adv}} = 0.1$"),
    ("ablation_adv_weight_0p5", r"$\lambda_{\mathrm{adv}} = 0.5$"),
    ("ablation_adv_weight_1p0", r"$\lambda_{\mathrm{adv}} = 1.0$"),
]


def table_ablations(index, dataset: str, split: str, significance: Dict[str, Any]) -> str:
    rows: List[str] = [r"Variant & Macro-F1 & $\Delta$ & $p$ & Params \\", r"\midrule"]
    reference = index.get(("ablation_full", dataset, split)) or index.get(("flowconx_main", dataset, split))
    reference_mean = (reference or {}).get("heads", {}).get("prototype", {}).get("macro_f1", {}).get("mean")
    lookup = _significance_lookup(significance)

    for experiment, label in ABLATION_ROWS:
        group = index.get((experiment, dataset, split))
        if group is None and experiment == "ablation_full":
            group = reference
        if group is None:
            rows.append(f"{label} & {TODO} & {TODO} & {TODO} & {TODO} \\\\")
            continue
        stats = group.get("heads", {}).get("prototype", {}).get("macro_f1", {})
        mean = stats.get("mean")
        delta = (
            f"{mean - reference_mean:+.3f}"
            if mean is not None and reference_mean is not None and experiment != "ablation_full"
            else "---"
        )
        entry = lookup.get((experiment, dataset, split))
        if entry is None:
            p_cell = NOT_APPLICABLE if experiment == "ablation_full" else TODO
        else:
            correction = entry.get("correction", {})
            p_value = entry.get("p_value")
            if p_value is not None and np.isfinite(p_value):
                marker = r"$^{*}$" if correction.get("significant") else ""
                p_cell = f"{p_value:.3g}{marker}"
            elif correction.get("undetermined"):
                # The test ran and declined: too few seeds for it to have power.
                # Rendering this as TODO would claim the run had not happened.
                p_cell = UNDETERMINED
            else:
                p_cell = TODO
        params = group.get("extras", {}).get("n_parameters", {}).get("mean")
        params_cell = f"{int(params):,}".replace(",", r"\,") if params else TODO
        rows.append(f"{label} & {fmt(mean, stats.get('std'))} & {delta} & {p_cell} & {params_cell} \\\\")

    return table_wrapper(
        "\n".join(rows),
        caption=(
            "\\textbf{Partial ablation family.} Embedding choice and the adversarial weight sweep, at "
            "the reduced ablation budget (10 epochs on a seeded stratified 72{,}000-row subsample), "
            "mean $\\pm$ std over seeds. $\\Delta$ is the change in macro-F1 against the full model. "
            "$p$ is a Wilcoxon signed-rank test across seeds, Holm-Bonferroni corrected within this "
            "family; $^{*}$ marks comparisons surviving the correction at $\\alpha = 0.05$, and "
            "\\emph{n.d.} marks comparisons the test declined to make --- at three seeds its minimum "
            "achievable $p$-value is $0.25$, so it has no power at any effect size. Those rows are "
            "reported with effect sizes and seed spreads instead, and are not claimed as significant. "
            "The fusion variants, loss-term ablations, and temperature, margin and input-budget sweeps "
            "were \\emph{not run}: they were designed to explain why the model wins the closed-set "
            "comparison, and it does not win it. See \\texttt{paper/RESULTS.md} for the full list of "
            "omitted configurations and the command that would run them."
        ),
        label="tab:ablation",
        columns="lcccc",
    )


def _significance_lookup(significance: Dict[str, Any]) -> Dict[Tuple[str, str, str], Dict[str, Any]]:
    out: Dict[Tuple[str, str, str], Dict[str, Any]] = {}
    for family in significance.get("families", []):
        for comparison in family.get("comparisons", []):
            key = (comparison.get("experiment"), comparison.get("dataset"), comparison.get("split"))
            if all(key):
                out[key] = comparison
    return out


# --------------------------------------------------------------------------
# Table 4: deployment cost.
# --------------------------------------------------------------------------


def table_cost(index, dataset: str, split: str) -> str:
    rows: List[str] = [
        r"Method & p50 (ms) & p95 (ms) & p99 (ms) & Flows/s & Params & Size (MB) & New class \\",
        r"\midrule",
    ]
    candidates = [("flowconx_main", "FlowCon-X")] + [
        (f"flowconx_main_baseline_{name}", PRETTY.get(name, name))
        for name in ("deeppacket_cnn", "fsnet", "lstm_attention", "mlp_stats")
    ]
    for experiment, label in candidates:
        group = index.get((experiment, dataset, split))
        if group is None:
            rows.append(f"{label} & " + " & ".join([TODO] * 7) + r" \\")
            continue
        extras = group.get("extras", {})

        def value(name: str, scale: float = 1.0, places: int = 2) -> str:
            stats = extras.get(name)
            if not stats or not np.isfinite(stats.get("mean", float("nan"))):
                return TODO
            return f"{stats['mean'] * scale:.{places}f}"

        _ = value

        params = extras.get("n_parameters", {}).get("mean")
        # The cost asymmetry the paper's enrollment claim rests on.
        enrollment = r"$k$ fwd passes" if experiment == "flowconx_main" else "fine-tune"
        rows.append(
            f"{label} & {value('latency_p50_ms')} & {value('latency_p95_ms')} & {value('latency_p99_ms')} & "
            f"{value('throughput_flows_per_s', places=0)} & "
            + (f"{int(params):,}".replace(",", r"\,") if params else TODO)
            + f" & {value('model_size_bytes', 1e-6, 1)} & {enrollment} \\\\"
        )
    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Deployment cost, measured on identical hardware. Latency percentiles are end-to-end -- stored "
            "record in, decision out, including feature construction -- at batch size 1, not a mean of the "
            "forward pass alone. The last column is the cost of adding one new application: a prototype "
            "update needs $k$ forward passes, a softmax classifier needs a fine-tuning run."
        ),
        label="tab:cost",
        columns="lccccccc",
    )


# --------------------------------------------------------------------------
# Table 5: open-set rejection. The one surviving modelling claim.
# --------------------------------------------------------------------------

SCORER_LABEL = {
    "prototype_cosine": r"Prototype cosine \textbf{(ours)}",
    "softmax_msp": "Max softmax probability",
    "energy": "Energy score",
    "mahalanobis": "Mahalanobis distance",
}


def table_open_set(results_root: Path) -> str:
    """AUROC and FPR@95TPR for every rejection rule, on one frozen embedding."""
    import statistics

    runs = _runs_with(results_root, "open_set")
    gathered: Dict[str, Dict[str, List[float]]] = {}
    n_known = n_unknown = 0
    held_out: List[str] = []
    for payload in runs:
        block = payload["open_set"]
        n_known, n_unknown = block["n_known_test"], block["n_unknown_test"]
        held_out = block.get("unknown_apps", [])
        for name, scorer in block["scorers"].items():
            bucket = gathered.setdefault(name, {"auroc": [], "fpr": []})
            bucket["auroc"].append(float(scorer["auroc"]))
            bucket["fpr"].append(float(scorer["fpr_at_95tpr"]))

    rows: List[str] = [r"Rejection rule & AUROC $\uparrow$ & FPR@95TPR $\downarrow$ \\", r"\midrule"]
    if not gathered:
        rows.append(f"All rules & {TODO} & {TODO} \\\\")
    else:
        for name in ("prototype_cosine", "softmax_msp", "energy", "mahalanobis"):
            values = gathered.get(name)
            label = SCORER_LABEL.get(name, latex_escape(name))
            if not values:
                rows.append(f"{label} & {TODO} & {TODO} \\\\")
                continue

            def stat(key: str) -> str:
                series = values[key]
                spread = statistics.stdev(series) if len(series) > 1 else None
                return fmt(statistics.mean(series), spread)

            rows.append(f"{label} & {stat('auroc')} & {stat('fpr')} \\\\")

    n_seeds = len(runs)
    detail = (
        f"{n_unknown:,} unknown against {n_known:,} known test flows, "
        f"held-out applications: {', '.join(latex_escape(a) for a in held_out)}. "
        if gathered
        else ""
    )
    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Open-set rejection of applications never seen in training, mean $\\pm$ std over "
            f"{n_seeds} seed(s). {detail}"
            "All four rules score the \\emph{same} frozen embedding, so the comparison isolates the "
            "rejection rule rather than the representation. FPR@95TPR is the column to read: the AUROC "
            "gap between prototype and softmax is within the seed spread, while the false-accept gap at "
            "matched true-positive rate is roughly twice it. Mahalanobis on the same embedding is "
            "statistically indistinguishable from the prototype rule, so the claim is that "
            "\\emph{distance-based rejection beats softmax thresholding}, not that ours is the best "
            "distance rule."
        ),
        label="tab:open-set",
        columns="lcc",
    )


# --------------------------------------------------------------------------
# Figures
# --------------------------------------------------------------------------


def _style():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "figure.figsize": (3.4, 2.4),
            "font.size": 8,
            "axes.labelsize": 8,
            "axes.titlesize": 8,
            "legend.fontsize": 7,
            "xtick.labelsize": 7,
            "ytick.labelsize": 7,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": True,
            "grid.alpha": 0.25,
            "grid.linewidth": 0.5,
            "lines.linewidth": 1.4,
            "lines.markersize": 3.5,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.02,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    return plt


def _runs_with(results_root: Path, key: str) -> List[Dict[str, Any]]:
    out = []
    for path in sorted(results_root.rglob("metrics.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        block = payload.get(key)
        if isinstance(block, dict) and block.get("status") == "ok":
            out.append(payload)
    return out


def figure_early_classification(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "early_classification")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    series: Dict[str, Dict[int, List[float]]] = {}
    for payload in runs:
        label = f"{payload['config']['data']['dataset']}"
        bucket = series.setdefault(label, {})
        for point in payload["early_classification"]["curve"]:
            bucket.setdefault(int(point["observed_packets"]), []).append(float(point["macro_f1"]))
    for i, (label, points) in enumerate(sorted(series.items())):
        budgets = sorted(points)
        means = [float(np.mean(points[b])) for b in budgets]
        stds = [float(np.std(points[b])) for b in budgets]
        axis.errorbar(budgets, means, yerr=stds, marker="o", color=PALETTE[i % len(PALETTE)], label=label, capsize=2)
    axis.set_xlabel("Observed packets")
    axis.set_ylabel("Macro-F1")
    axis.set_xscale("log")
    axis.legend(frameon=False)
    path = out_dir / "early_classification.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_enrollment(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "few_shot")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    points: Dict[int, List[float]] = {}
    for payload in runs:
        for entry in payload["few_shot"].get("service_enrollment", []):
            points.setdefault(int(entry["shots"]), []).append(float(entry["macro_f1_mean"]))
    if not points:
        plt.close(figure)
        return None
    shots = sorted(points)
    axis.errorbar(
        shots,
        [float(np.mean(points[k])) for k in shots],
        yerr=[float(np.std(points[k])) for k in shots],
        marker="o",
        color=PALETTE[0],
        capsize=2,
        label="FlowCon-X (frozen encoder)",
    )
    axis.set_xlabel("Labelled flows per enrolled class")
    axis.set_ylabel("Macro-F1")
    axis.set_xscale("log")
    axis.legend(frameon=False)
    path = out_dir / "enrollment_curve.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_robustness(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "robustness")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots(figsize=(3.4, 2.6))
    rows: Dict[str, List[Tuple[float, float]]] = {}
    for payload in runs:
        for entry in payload["robustness"]["perturbations"]:
            if entry["name"] == "clean":
                continue
            rows.setdefault(entry["name"], []).append(
                (float(entry.get("byte_overhead_ratio", 1.0)), float(entry["macro_f1"]))
            )
    if not rows:
        plt.close(figure)
        return None
    for i, (name, values) in enumerate(sorted(rows.items())):
        overhead = float(np.mean([v[0] for v in values]))
        score = float(np.mean([v[1] for v in values]))
        axis.scatter(overhead, score, color=PALETTE[i % len(PALETTE)], label=name.replace("_", " "), zorder=3)
    axis.set_xlabel("Byte overhead (x baseline)")
    axis.set_ylabel("Macro-F1 under defence")
    axis.legend(frameon=False, ncol=2, fontsize=5.5)
    path = out_dir / "robustness_overhead.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_adversarial_tradeoff(results_root: Path, out_dir: Path) -> Optional[Path]:
    """Nuisance leakage against task performance, as the adversarial weight varies.

    Needs at least two *distinct* weights. With one weight the plot is two
    points stacked on a single x-value, which reads as a trade-off curve while
    showing no trade-off at all -- the sweep behind it (configs/ablations/
    adv_weight_*.yaml) simply has not run.
    """
    points: List[Tuple[float, float, float]] = []
    for path in sorted(results_root.rglob("metrics.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        tradeoff = (payload.get("probes") or {}).get("tradeoff")
        if not tradeoff:
            continue
        points.append(
            (
                float(payload["config"]["loss"]["lambda_adversarial"]),
                float(tradeoff["nuisance_above_majority_mlp"]),
                float(tradeoff["task_macro_f1_mlp"]),
            )
        )
    weights = sorted({p[0] for p in points})
    if len(weights) < 2:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    nuisance = [float(np.mean([p[1] for p in points if p[0] == w])) for w in weights]
    task = [float(np.mean([p[2] for p in points if p[0] == w])) for w in weights]
    axis.plot(weights, nuisance, marker="o", color=PALETTE[1], label="Nuisance probe above chance")
    axis.plot(weights, task, marker="s", color=PALETTE[0], label="Task macro-F1")
    axis.set_xlabel(r"Adversarial weight $\lambda_{\mathrm{adv}}$")
    axis.set_ylabel("Score")
    axis.legend(frameon=False)
    path = out_dir / "adversarial_tradeoff.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


# --------------------------------------------------------------------------


def load_audit(results_root: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for path in sorted((results_root / "audit").glob("*/audit_summary.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        out[payload["dataset"]] = payload
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate every paper table and figure.")
    parser.add_argument("--results", default="results")
    parser.add_argument("--out", default="paper")
    parser.add_argument("--datasets", nargs="*", default=["cesnet_quic22", "fiveg_traffic"])
    parser.add_argument("--main-split", default="session_disjoint")
    args = parser.parse_args(argv)

    results_root = Path(args.results)
    out_root = Path(args.out)
    tables_dir = out_root / "tables"
    figures_dir = out_root / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    summary = aggregate(results_root)
    index = _index(summary["groups"])
    audit = load_audit(results_root)
    significance_path = results_root / "significance.json"
    significance = json.loads(significance_path.read_text()) if significance_path.exists() else {}

    written: List[Tuple[Path, int]] = []

    def emit(name: str, content: str) -> None:
        path = tables_dir / name
        path.write_text(content, encoding="utf-8")
        written.append((path, content.count(TODO)))

    emit("split_contrast.tex", table_split_contrast(index, args.datasets, audit))
    for dataset in args.datasets:
        emit(f"main_comparison_{dataset}.tex", table_main_comparison(index, audit, dataset, args.main_split))
    emit("ablation.tex", table_ablations(index, "cesnet_quic22", args.main_split, significance))
    emit("cost.tex", table_cost(index, "cesnet_quic22", args.main_split))
    emit("open_set.tex", table_open_set(results_root))

    figures: List[Optional[Path]] = []
    try:
        figures = [
            figure_early_classification(results_root, figures_dir),
            figure_enrollment(results_root, figures_dir),
            figure_robustness(results_root, figures_dir),
            figure_adversarial_tradeoff(results_root, figures_dir),
        ]
    except ImportError:
        print("matplotlib is not installed; tables written, figures skipped", file=sys.stderr)

    print(f"aggregated {summary['n_runs']} runs into {len(summary['groups'])} groups\n")
    total_todo = 0
    for path, todos in written:
        total_todo += todos
        marker = f"  <- {todos} TODO cell(s)" if todos else ""
        print(f"  {path}{marker}")
    for figure in figures:
        if figure:
            print(f"  {figure}")
    missing_figures = sum(1 for f in figures if f is None)
    if missing_figures:
        print(f"\n  {missing_figures} figure(s) not drawn: the runs behind them have not happened yet.")
    if total_todo:
        print(
            f"\n{total_todo} TODO cell(s) remain. Each is a run that has not happened. "
            "They are never filled with a plausible value."
        )
    else:
        print("\nEvery cell is populated from a run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
