#!/usr/bin/env python3
"""Regenerate every table and figure from results/.

    python scripts/make_paper_assets.py --results results --out paper

Tables are LaTeX, figures are vector PDF, and neither is ever edited by hand.
A cell whose run did not happen is written as ``TODO``; it is never filled
with a plausible value, and the script prints a summary of how many TODOs
remain so that an incomplete table cannot be mistaken for a complete one.

Every claim of "better" is looked up in results/significance.json. A
comparison absent from that file is rendered without a significance marker,
not with an optimistic one.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np  # noqa: E402

from flowconx.analysis.aggregate import aggregate  # noqa: E402

TODO = r"\textsc{todo}"

# Colourblind-safe (Okabe-Ito). Used for every figure so the paper reads as
# one document rather than as a collection of default matplotlib styles.
PALETTE = ["#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00", "#56B4E9", "#F0E442", "#000000"]


def latex_escape(text: str) -> str:
    for old, new in (("_", r"\_"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(old, new)
    return text


def fmt(mean: Optional[float], std: Optional[float] = None, places: int = 3) -> str:
    if mean is None or not np.isfinite(mean):
        return TODO
    if std is None or not np.isfinite(std):
        return f"{mean:.{places}f}"
    return f"{mean:.{places}f} $\\pm$ {std:.{places}f}"


def table_wrapper(body: str, caption: str, label: str, columns: str) -> str:
    return "\n".join(
        [
            "% Generated by scripts/make_paper_assets.py. Do not edit by hand.",
            r"\begin{table}[t]",
            r"\centering",
            r"\small",
            f"\\begin{{tabular}}{{{columns}}}",
            r"\toprule",
            body,
            r"\bottomrule",
            r"\end{tabular}",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            r"\end{table}",
            "",
        ]
    )


def _cell(group: Optional[Dict[str, Any]], head: str, metric: str = "macro_f1") -> str:
    """A table cell, or TODO when the run behind it has not happened."""
    if not group:
        return TODO
    stats = group.get("heads", {}).get(head, {}).get(metric)
    if not stats:
        return TODO
    return fmt(stats.get("mean"), stats.get("std"))


def _index(groups: Sequence[Dict[str, Any]]) -> Dict[Tuple[str, str, str], Dict[str, Any]]:
    return {(g["experiment"], g["dataset"], g["split"]): g for g in groups}


# --------------------------------------------------------------------------
# Table 1: split protocol contrast. The measurement contribution.
# --------------------------------------------------------------------------

SPLIT_ORDER = ["random_flow", "session_disjoint", "temporal", "server_disjoint"]
SPLIT_LABEL = {
    "random_flow": "Random flow",
    "session_disjoint": "Session-disjoint",
    "temporal": "Temporal",
    "server_disjoint": "Server-disjoint",
}


def table_split_contrast(index, datasets: Sequence[str], audit: Dict[str, Any]) -> str:
    """How much the field's usual protocol inflates a published-style number."""
    rows: List[str] = []
    header = ["Split protocol"] + [latex_escape(d) for d in datasets]
    rows.append(" & ".join(header) + r" \\")
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{%d}{l}{\emph{FlowCon-X (prototype head)}} \\" % (len(datasets) + 1))
    for split in SPLIT_ORDER:
        cells = []
        for dataset in datasets:
            group = None
            for (experiment, ds, sp), candidate in index.items():
                if ds == dataset and sp == split and experiment.startswith("flowconx_"):
                    group = candidate
                    break
            cells.append(_cell(group, "prototype") if group else TODO)
        rows.append(f"{SPLIT_LABEL[split]} & " + " & ".join(cells) + r" \\")

    if audit:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{%d}{l}{\emph{AppScanner (2016), identical splits}} \\" % (len(datasets) + 1))
        for split in SPLIT_ORDER:
            cells = []
            for dataset in datasets:
                value = (
                    audit.get(dataset, {})
                    .get("splits", {})
                    .get(split, {})
                    .get("baselines", {})
                    .get("appscanner", {})
                    .get("macro_f1")
                )
                cells.append(fmt(value) if isinstance(value, (int, float)) else TODO)
            rows.append(f"{SPLIT_LABEL[split]} & " + " & ".join(cells) + r" \\")

    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Macro-F1 under four split protocols. The random-flow row is the field's usual protocol and "
            "is reported only as a contrast: correlated flows from one capture session appear on both "
            "sides of it. The gap between it and the session-disjoint row is the inflation that protocol "
            "produces, and it applies to a 2016 statistical baseline as much as to our model."
        ),
        label="tab:split-contrast",
        columns="l" + "c" * len(datasets),
    )


# --------------------------------------------------------------------------
# Table 2: main comparison against every baseline we could run.
# --------------------------------------------------------------------------

BASELINE_TIERS = [
    ("Identifier shortcuts", ["port_only", "sni_only", "server_ip_only", "server_asn_only", "protocol_only"]),
    ("Classical statistical", ["five_stat", "size_histogram", "cumul", "appscanner", "kfp"]),
    ("Deep, non-pretrained", ["deeppacket_cnn", "fsnet", "lstm_attention", "mlp_stats"]),
]
PRETTY = {
    "port_only": "Destination port only",
    "sni_only": "SNI string only",
    "server_ip_only": "Server IP / prefix only",
    "server_asn_only": "Server AS only",
    "protocol_only": "Transport protocol only",
    "five_stat": "5 flow statistics (RF)",
    "size_histogram": "Packet-size histogram (XGB)",
    "cumul": "CUMUL",
    "appscanner": "AppScanner",
    "kfp": "$k$-fingerprinting",
    "deeppacket_cnn": "DeepPacket-style CNN",
    "fsnet": "FS-Net",
    "lstm_attention": "Bi-LSTM + attention",
    "mlp_stats": "Flow-statistics MLP",
    "majority_class": "Majority class",
}


def table_main_comparison(index, audit, dataset: str, split: str) -> str:
    rows: List[str] = [r"Method & Macro-F1 & Balanced acc. & Params \\", r"\midrule"]
    audit_split = audit.get(dataset, {}).get("splits", {}).get(split, {}).get("baselines", {})

    floor = audit_split.get("majority_class", {})
    rows.append(
        f"{PRETTY['majority_class']} & {fmt(floor.get('macro_f1'))} & "
        f"{fmt(floor.get('balanced_accuracy'))} & --- \\\\"
    )
    for tier, families in BASELINE_TIERS:
        rows.append(r"\midrule")
        rows.append(rf"\multicolumn{{4}}{{l}}{{\emph{{{tier}}}}} \\")
        for family in families:
            if family in audit_split:
                entry = audit_split[family]
                rows.append(
                    f"{PRETTY.get(family, latex_escape(family))} & {fmt(entry.get('macro_f1'))} & "
                    f"{fmt(entry.get('balanced_accuracy'))} & --- \\\\"
                )
                continue
            group = index.get((f"baseline_{family}", dataset, split))
            if group is None:
                rows.append(f"{PRETTY.get(family, latex_escape(family))} & {TODO} & {TODO} & {TODO} \\\\")
                continue
            params = group.get("extras", {}).get("n_parameters", {}).get("mean")
            rows.append(
                f"{PRETTY.get(family, latex_escape(family))} & {_cell(group, 'softmax')} & "
                f"{_cell(group, 'softmax', 'balanced_accuracy')} & "
                f"{int(params):,} \\\\".replace(",", r"\,")
                if params
                else f"{PRETTY.get(family, latex_escape(family))} & {_cell(group, 'softmax')} & "
                f"{_cell(group, 'softmax', 'balanced_accuracy')} & {TODO} \\\\"
            )

    rows.append(r"\midrule")
    ours = index.get(("flowconx_main", dataset, split))
    params = (ours or {}).get("extras", {}).get("n_parameters", {}).get("mean")
    rows.append(
        rf"\textbf{{FlowCon-X}} & \textbf{{{_cell(ours, 'prototype')}}} & "
        rf"{_cell(ours, 'prototype', 'balanced_accuracy')} & "
        + (f"{int(params):,}".replace(",", r"\,") if params else TODO)
        + r" \\"
    )
    return table_wrapper(
        "\n".join(rows),
        caption=(
            f"Main comparison on {latex_escape(dataset)} under the {SPLIT_LABEL.get(split, split).lower()} "
            "protocol, mean $\\pm$ std over seeds, every method on the identical committed splits. "
            "Identifier shortcuts are included deliberately: if one of them approaches the rest, the "
            "benchmark is not measuring traffic analysis. Pre-trained byte-level transformers "
            "(ET-BERT, YaTC, CLE-TFE) are absent because our records retain no payload; see "
            r"\texttt{flowconx/baselines/WHY\_NOT\_RUN.md}."
        ),
        label=f"tab:main-{dataset}",
        columns="lccc",
    )


# --------------------------------------------------------------------------
# Table 3: ablations, with significance.
# --------------------------------------------------------------------------

ABLATION_ROWS = [
    ("ablation_full", "Full model"),
    ("ablation_no_flow_metric", r"$-$ flow-level metric objective \textbf{(headline)}"),
    ("ablation_no_dual_encoder", r"$-$ dual encoder"),
    ("ablation_fusion_concat", r"cross-attention $\rightarrow$ concatenation"),
    ("ablation_fusion_gated_sum", r"cross-attention $\rightarrow$ gated sum"),
    ("ablation_fusion_late", r"cross-attention $\rightarrow$ late fusion"),
    ("ablation_no_adversarial", r"$-$ adversarial nuisance removal"),
    ("ablation_no_disentangle", r"$-$ disentanglement term"),
    ("ablation_no_prototype", r"$-$ prototype alignment"),
    ("ablation_contrastive_only", "contrastive only"),
    ("ablation_margin_only", "margin only"),
    ("ablation_joint_training", "joint instead of two-stage"),
    ("ablation_classify_z_app", r"classify from $z_{\mathrm{app}}$"),
    ("ablation_classify_z_network", r"classify from $z_{\mathrm{net}}$"),
    ("ablation_classify_z_concat", r"classify from $z_{\mathrm{app}} \| z_{\mathrm{net}}$"),
    ("ablation_capacity_matched_small", "reduced width (capacity control)"),
]


def table_ablations(index, dataset: str, split: str, significance: Dict[str, Any]) -> str:
    rows: List[str] = [r"Variant & Macro-F1 & $\Delta$ & $p$ & Params \\", r"\midrule"]
    reference = index.get(("ablation_full", dataset, split)) or index.get(("flowconx_main", dataset, split))
    reference_mean = (reference or {}).get("heads", {}).get("prototype", {}).get("macro_f1", {}).get("mean")
    lookup = _significance_lookup(significance)

    for experiment, label in ABLATION_ROWS:
        group = index.get((experiment, dataset, split))
        if group is None and experiment == "ablation_full":
            group = reference
        if group is None:
            rows.append(f"{label} & {TODO} & {TODO} & {TODO} & {TODO} \\\\")
            continue
        stats = group.get("heads", {}).get("prototype", {}).get("macro_f1", {})
        mean = stats.get("mean")
        delta = (
            f"{mean - reference_mean:+.3f}"
            if mean is not None and reference_mean is not None and experiment != "ablation_full"
            else "---"
        )
        entry = lookup.get((experiment, dataset, split))
        if entry is None:
            p_cell = "---" if experiment == "ablation_full" else TODO
        else:
            marker = r"$^{*}$" if entry.get("correction", {}).get("significant") else ""
            p_value = entry.get("p_value")
            p_cell = (f"{p_value:.3g}" + marker) if p_value is not None and np.isfinite(p_value) else TODO
        params = group.get("extras", {}).get("n_parameters", {}).get("mean")
        params_cell = f"{int(params):,}".replace(",", r"\,") if params else TODO
        rows.append(f"{label} & {fmt(mean, stats.get('std'))} & {delta} & {p_cell} & {params_cell} \\\\")

    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Component ablations, mean $\\pm$ std over seeds. $\\Delta$ is the change in macro-F1 against "
            "the full model. $p$ is a Wilcoxon signed-rank test across seeds against the full model, "
            "Holm-Bonferroni corrected across this family; $^{*}$ marks comparisons that survive the "
            "correction at $\\alpha = 0.05$. Parameter counts are given so that a difference is not "
            "attributable to capacity alone."
        ),
        label="tab:ablation",
        columns="lcccc",
    )


def _significance_lookup(significance: Dict[str, Any]) -> Dict[Tuple[str, str, str], Dict[str, Any]]:
    out: Dict[Tuple[str, str, str], Dict[str, Any]] = {}
    for family in significance.get("families", []):
        for comparison in family.get("comparisons", []):
            key = (comparison.get("experiment"), comparison.get("dataset"), comparison.get("split"))
            if all(key):
                out[key] = comparison
    return out


# --------------------------------------------------------------------------
# Table 4: deployment cost.
# --------------------------------------------------------------------------


def table_cost(index, dataset: str, split: str) -> str:
    rows: List[str] = [
        r"Method & p50 (ms) & p95 (ms) & p99 (ms) & Flows/s & Params & Size (MB) & New class \\",
        r"\midrule",
    ]
    candidates = [("flowconx_main", "FlowCon-X")] + [
        (f"baseline_{name}", PRETTY.get(name, name))
        for name in ("deeppacket_cnn", "fsnet", "lstm_attention", "mlp_stats")
    ]
    for experiment, label in candidates:
        group = index.get((experiment, dataset, split))
        if group is None:
            rows.append(f"{label} & " + " & ".join([TODO] * 7) + r" \\")
            continue
        extras = group.get("extras", {})

        def value(name: str, scale: float = 1.0, places: int = 2) -> str:
            stats = extras.get(name)
            if not stats or not np.isfinite(stats.get("mean", float("nan"))):
                return TODO
            return f"{stats['mean'] * scale:.{places}f}"

        params = extras.get("n_parameters", {}).get("mean")
        # The cost asymmetry the paper's enrollment claim rests on.
        enrollment = r"$k$ fwd passes" if experiment == "flowconx_main" else "fine-tune"
        rows.append(
            f"{label} & {value('latency_p50_ms')} & {value('latency_p95_ms')} & {value('latency_p99_ms')} & "
            f"{value('throughput_flows_per_s', places=0)} & "
            + (f"{int(params):,}".replace(",", r"\,") if params else TODO)
            + f" & {value('model_size_bytes', 1e-6, 1)} & {enrollment} \\\\"
        )
    return table_wrapper(
        "\n".join(rows),
        caption=(
            "Deployment cost, measured on identical hardware. Latency percentiles are end-to-end -- stored "
            "record in, decision out, including feature construction -- at batch size 1, not a mean of the "
            "forward pass alone. The last column is the cost of adding one new application: a prototype "
            "update needs $k$ forward passes, a softmax classifier needs a fine-tuning run."
        ),
        label="tab:cost",
        columns="lccccccc",
    )


# --------------------------------------------------------------------------
# Figures
# --------------------------------------------------------------------------


def _style():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "figure.figsize": (3.4, 2.4),
            "font.size": 8,
            "axes.labelsize": 8,
            "axes.titlesize": 8,
            "legend.fontsize": 7,
            "xtick.labelsize": 7,
            "ytick.labelsize": 7,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": True,
            "grid.alpha": 0.25,
            "grid.linewidth": 0.5,
            "lines.linewidth": 1.4,
            "lines.markersize": 3.5,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.02,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    return plt


def _runs_with(results_root: Path, key: str) -> List[Dict[str, Any]]:
    out = []
    for path in sorted(results_root.rglob("metrics.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        block = payload.get(key)
        if isinstance(block, dict) and block.get("status") == "ok":
            out.append(payload)
    return out


def figure_early_classification(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "early_classification")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    series: Dict[str, Dict[int, List[float]]] = {}
    for payload in runs:
        label = f"{payload['config']['data']['dataset']}"
        bucket = series.setdefault(label, {})
        for point in payload["early_classification"]["curve"]:
            bucket.setdefault(int(point["observed_packets"]), []).append(float(point["macro_f1"]))
    for i, (label, points) in enumerate(sorted(series.items())):
        budgets = sorted(points)
        means = [float(np.mean(points[b])) for b in budgets]
        stds = [float(np.std(points[b])) for b in budgets]
        axis.errorbar(budgets, means, yerr=stds, marker="o", color=PALETTE[i % len(PALETTE)], label=label, capsize=2)
    axis.set_xlabel("Observed packets")
    axis.set_ylabel("Macro-F1")
    axis.set_xscale("log")
    axis.legend(frameon=False)
    path = out_dir / "early_classification.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_enrollment(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "few_shot")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    points: Dict[int, List[float]] = {}
    for payload in runs:
        for entry in payload["few_shot"].get("service_enrollment", []):
            points.setdefault(int(entry["shots"]), []).append(float(entry["macro_f1_mean"]))
    if not points:
        plt.close(figure)
        return None
    shots = sorted(points)
    axis.errorbar(
        shots,
        [float(np.mean(points[k])) for k in shots],
        yerr=[float(np.std(points[k])) for k in shots],
        marker="o",
        color=PALETTE[0],
        capsize=2,
        label="FlowCon-X (frozen encoder)",
    )
    axis.set_xlabel("Labelled flows per enrolled class")
    axis.set_ylabel("Macro-F1")
    axis.set_xscale("log")
    axis.legend(frameon=False)
    path = out_dir / "enrollment_curve.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_robustness(results_root: Path, out_dir: Path) -> Optional[Path]:
    runs = _runs_with(results_root, "robustness")
    if not runs:
        return None
    plt = _style()
    figure, axis = plt.subplots(figsize=(3.4, 2.6))
    rows: Dict[str, List[Tuple[float, float]]] = {}
    for payload in runs:
        for entry in payload["robustness"]["perturbations"]:
            if entry["name"] == "clean":
                continue
            rows.setdefault(entry["name"], []).append(
                (float(entry.get("byte_overhead_ratio", 1.0)), float(entry["macro_f1"]))
            )
    if not rows:
        plt.close(figure)
        return None
    for i, (name, values) in enumerate(sorted(rows.items())):
        overhead = float(np.mean([v[0] for v in values]))
        score = float(np.mean([v[1] for v in values]))
        axis.scatter(overhead, score, color=PALETTE[i % len(PALETTE)], label=name.replace("_", " "), zorder=3)
    axis.set_xlabel("Byte overhead (x baseline)")
    axis.set_ylabel("Macro-F1 under defence")
    axis.legend(frameon=False, ncol=2, fontsize=5.5)
    path = out_dir / "robustness_overhead.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


def figure_adversarial_tradeoff(results_root: Path, out_dir: Path) -> Optional[Path]:
    points: List[Tuple[float, float, float]] = []
    for path in sorted(results_root.rglob("metrics.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        tradeoff = (payload.get("probes") or {}).get("tradeoff")
        if not tradeoff:
            continue
        points.append(
            (
                float(payload["config"]["loss"]["lambda_adversarial"]),
                float(tradeoff["nuisance_above_majority_mlp"]),
                float(tradeoff["task_macro_f1_mlp"]),
            )
        )
    if len(points) < 2:
        return None
    plt = _style()
    figure, axis = plt.subplots()
    weights = sorted({p[0] for p in points})
    nuisance = [float(np.mean([p[1] for p in points if p[0] == w])) for w in weights]
    task = [float(np.mean([p[2] for p in points if p[0] == w])) for w in weights]
    axis.plot(weights, nuisance, marker="o", color=PALETTE[1], label="Nuisance probe above chance")
    axis.plot(weights, task, marker="s", color=PALETTE[0], label="Task macro-F1")
    axis.set_xlabel(r"Adversarial weight $\lambda_{\mathrm{adv}}$")
    axis.set_ylabel("Score")
    axis.legend(frameon=False)
    path = out_dir / "adversarial_tradeoff.pdf"
    figure.savefig(path)
    plt.close(figure)
    return path


# --------------------------------------------------------------------------


def load_audit(results_root: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for path in sorted((results_root / "audit").glob("*/audit_summary.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        out[payload["dataset"]] = payload
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate every paper table and figure.")
    parser.add_argument("--results", default="results")
    parser.add_argument("--out", default="paper")
    parser.add_argument("--datasets", nargs="*", default=["cesnet_quic22", "fiveg_traffic"])
    parser.add_argument("--main-split", default="session_disjoint")
    args = parser.parse_args(argv)

    results_root = Path(args.results)
    out_root = Path(args.out)
    tables_dir = out_root / "tables"
    figures_dir = out_root / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    summary = aggregate(results_root)
    index = _index(summary["groups"])
    audit = load_audit(results_root)
    significance_path = results_root / "significance.json"
    significance = json.loads(significance_path.read_text()) if significance_path.exists() else {}

    written: List[Tuple[Path, int]] = []

    def emit(name: str, content: str) -> None:
        path = tables_dir / name
        path.write_text(content, encoding="utf-8")
        written.append((path, content.count(TODO)))

    emit("split_contrast.tex", table_split_contrast(index, args.datasets, audit))
    for dataset in args.datasets:
        emit(f"main_comparison_{dataset}.tex", table_main_comparison(index, audit, dataset, args.main_split))
    emit("ablation.tex", table_ablations(index, "cesnet_quic22", args.main_split, significance))
    emit("cost.tex", table_cost(index, "cesnet_quic22", args.main_split))

    figures: List[Optional[Path]] = []
    try:
        figures = [
            figure_early_classification(results_root, figures_dir),
            figure_enrollment(results_root, figures_dir),
            figure_robustness(results_root, figures_dir),
            figure_adversarial_tradeoff(results_root, figures_dir),
        ]
    except ImportError:
        print("matplotlib is not installed; tables written, figures skipped", file=sys.stderr)

    print(f"aggregated {summary['n_runs']} runs into {len(summary['groups'])} groups\n")
    total_todo = 0
    for path, todos in written:
        total_todo += todos
        marker = f"  <- {todos} TODO cell(s)" if todos else ""
        print(f"  {path}{marker}")
    for figure in figures:
        if figure:
            print(f"  {figure}")
    missing_figures = sum(1 for f in figures if f is None)
    if missing_figures:
        print(f"\n  {missing_figures} figure(s) not drawn: the runs behind them have not happened yet.")
    if total_todo:
        print(
            f"\n{total_todo} TODO cell(s) remain. Each is a run that has not happened. "
            "They are never filled with a plausible value."
        )
    else:
        print("\nEvery cell is populated from a run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
